### ISSUE TITLE
Unable to parse hhvm-master's phar.php

### ISSUE THREAD

**Issue by JoelMarcey** [fredemmott/definition-finder#18]
[HHVM's Phar.php line 1178](https://github.com/facebook/hhvm/blob/master/hphp/system/php/phar/Phar.php#L1178) was modified in a [commit](https://github.com/facebook/hhvm/commit/e0713e72a8c7b359ecf8d732b6b4efc9e32e0533#diff-b27b4d7c23c8fce110c08ead3cd1248c) recently to have a parameter type in `getIteratorFromList` like `array<string, PharFileInfo>`. 

Looks like we cannot handle that case here. Notice the line number in the exception is the exact line number of what I linked to above.

```
Fatal error: Uncaught exception 'HH\InvariantException' with message 'found two things that look like typehints for the same parameter at line 1178' in /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php:169
Stack trace:
#0 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php(169): HH\invariant_violation()
#1 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/FunctionAbstractConsumer.php(55): FredEmmott\DefinitionFinder\FunctionAbstractConsumer->consumeParameterList()
#2 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(202): FredEmmott\DefinitionFinder\FunctionAbstractConsumer->getBuilder()
#3 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#4 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php(84): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#5 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(194): FredEmmott\DefinitionFinder\ClassConsumer->getBuilder()
#6 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#7 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(12): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#8 /home/joelm/dev/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#9 /home/joelm/dev/user-documentation/src/build/RawYAMLBuildStep.php(46): FredEmmott\DefinitionFinder\FileParser::FromData()
#10 /home/joelm/dev/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#11 /home/joelm/dev/user-documentation/bin/build.php(62): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#12 /home/joelm/dev/user-documentation/bin/build.php(69): HHVM\UserDocumentation\build_site()
#13 {main}
```

**Comment by JoelMarcey** [comment]
I tested by changing the parameter to `array<string>` only and same error.

Then I removed the `<>` and just had `array` and all parsed fine.

**Comment by fredemmott** [comment]
Not that simple apparently :(

**Comment by fredemmott** [comment]
Phar.php has `<?php` but is not valid PHP code.
