### ISSUE TITLE
Consumer can't parse use statements divided by comma

### ISSUE THREAD

**Issue by guilhermegeek** [fredemmott/definition-finder#19]
Code Failling:

```php
use Test\Class1,
Test\Class2,
Test\Class3;
```
Error: 
```
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Unexpected token ','' in /home/the-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php:320
Stack trace:
#0 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(320): HH\invariant_violation()
#1 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(82): FredEmmott\DefinitionFinder\ScopeConsumer->consumeUseStatement()
#2 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/NamespaceConsumer.php(32): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#3 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(183): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#4 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#5 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(12): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#6 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#7 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(28): FredEmmott\DefinitionFinder\FileParser::FromData()
#8 /home/th-project/vendor/hackpack/hackunit/src/Test/SuiteBuilder.php(32): FredEmmott\DefinitionFinder\FileParser::FromFile()
#9 /home/th-project/vendor/hackpack/hackunit/src/HackUnit.php(23): HackPack\HackUnit\Test\SuiteBuilder->buildSuites()
#10 /home/th-project/vendor/hackpack/hackunit/src/Test/Loader.php(36): Closure$HackPack\HackUnit\HackUnit::run#2()
#11 /home/th-project/vendor/hackpack/hackunit/src/HackUnit.php(59): HackPack\HackUnit\Test\Loader->testSuites()
#12 /home/th-project/vendor/hackpack/hackunit/bin/hackunit(29): HackPack\HackUnit\HackUnit::run()
```

Code Working:

```php
use Test\Class1;
use Test\Class2;
use Test\Class3;`
```

I'm trying to fix this but i can't reproduce all tests properly, one is always failing. Can someone tell me if it's excepted?

```
1) FredEmmott\DefinitionFinder\Test\SelfTest::testELFSection with data set #27 ('ext.f1f713c9e000', '<?hh\n\n/**\n * Returns an array...ec;\n}\n')
FredEmmott\DefinitionFinder\ParseException: ext.f1f713c9e000:1397: expected a type

/hack/src/definition-finder/src/FileParser.php:19
/hack/src/definition-finder/src/FileParser.php:38
/hack/src/definition-finder/tests/SelfTest.php:39

Caused by
HH\InvariantException: expected a type

/hack/src/definition-finder/src/consumers/TypehintConsumer.php:147
/hack/src/definition-finder/src/consumers/TypehintConsumer.php:7
/hack/src/definition-finder/src/consumers/FunctionAbstractConsumer.php:62
/hack/src/definition-finder/src/consumers/ScopeConsumer.php:205
/hack/src/definition-finder/src/consumers/ScopeConsumer.php:156
/hack/src/definition-finder/src/consumers/NamespaceConsumer.php:32
/hack/src/definition-finder/src/consumers/ScopeConsumer.php:183
/hack/src/definition-finder/src/consumers/ScopeConsumer.php:156
/hack/src/definition-finder/src/FileParser.php:12
/hack/src/definition-finder/src/FileParser.php:38
/hack/src/definition-finder/tests/SelfTest.php:39
```

**Comment by fredemmott** [comment]
What version of HHVM are you using? That test makes sure that all of the PHP/Hack code bundled in HHVM itself is parsable.

**Comment by guilhermegeek** [comment]
I'm using 3.14.0-0 from pre-built packages

**Comment by fredemmott** [comment]
I recently moved, hopefully I'll have time to unpack my dev machine and look into this this weekend :/

**Comment by fredemmott** [comment]
Can't reproduce, but given that number I suspect it was incorrectly parsed given T_VEC
