### ISSUE TITLE
Classes with names of XHP tokens don't pass

### ISSUE THREAD

**Issue by simonwelsh** [fredemmott/definition-finder#35]
```hack
<?hh

class Category {}
```

Since `Category` generates a `T_XHP_CATEGORY` instead of a `T_STRING`, this leads to an error when parsing:
```
Next exception 'FredEmmott\DefinitionFinder\ParseException' with message '/home/vagrant/projects/wbooks/src/Model/Category.php:9: Unknown class token 0' in /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php:25
Stack trace:
#0 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php(42): FredEmmott\DefinitionFinder\FileParser->__construct()
#1 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php(32): FredEmmott\DefinitionFinder\FileParser::FromData()
#2 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/TreeParser.php(29): FredEmmott\DefinitionFinder\FileParser::FromFile()
#3 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/TreeParser.php(36): FredEmmott\DefinitionFinder\TreeParser->__construct()
#4 /home/vagrant/projects/wbooks/vendor/fredemmott/hack-router-codegen/src/Codegen.php(84): FredEmmott\DefinitionFinder\TreeParser::FromPath()
#5 /home/vagrant/projects/wbooks/src/UpdateCodegen.php(61): FredEmmott\HackRouter\Codegen::forTree()
#6 /home/vagrant/projects/wbooks/src/UpdateCodegen.php(117): UpdateCodegen::controllers()
#7 /home/vagrant/projects/wbooks/bin/update-codegen.php(5): UpdateCodegen::main()
#8 {main}
```

Will probably happen with all the other `T_XHP_` tokens.

**Comment by fredemmott** [comment]
Will hopefully look in the next few days; if you've got time for a PR, please include a test, and you probably just need to add a few things to https://github.com/fredemmott/definition-finder/blob/afb1359047189d74f2a3e1fe1a808e12011bc225/src/typedefs.php#L68

**Comment by HRMsimon** [comment]
Looks like `T_SUPER` as well
