### ISSUE TITLE
Can't parse abstract constants

### ISSUE THREAD

**Issue by simonwelsh** [fredemmott/definition-finder#36]
```hack
<?hh

abstract class Base {
  abstract const string NAME;
}
```

Gives
```
Next exception 'FredEmmott\DefinitionFinder\ParseException' with message '/home/vagrant/projects/wbooks/src/Model/Base.php:7: invalid constant definition' in /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php:25
Stack trace:
#0 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php(42): FredEmmott\DefinitionFinder\FileParser->__construct()
#1 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/FileParser.php(32): FredEmmott\DefinitionFinder\FileParser::FromData()
#2 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/TreeParser.php(29): FredEmmott\DefinitionFinder\FileParser::FromFile()
#3 /home/vagrant/projects/wbooks/vendor/fredemmott/definition-finder/src/TreeParser.php(36): FredEmmott\DefinitionFinder\TreeParser->__construct()
#4 /home/vagrant/projects/wbooks/vendor/fredemmott/hack-router-codegen/src/Codegen.php(84): FredEmmott\DefinitionFinder\TreeParser::FromPath()
#5 /home/vagrant/projects/wbooks/src/UpdateCodegen.php(61): FredEmmott\HackRouter\Codegen::forTree()
#6 /home/vagrant/projects/wbooks/src/UpdateCodegen.php(150): UpdateCodegen::controllers()
#7 /home/vagrant/projects/wbooks/bin/update-codegen.php(5): UpdateCodegen::main()
#8 {main}
```

**Comment by fredemmott** [comment]
Strangely enough it looks like we support abstract type constants, but not actual abstract constants >_<
