### ISSUE TITLE
'Unexpected token '('' when using namespace-relative names

### ISSUE THREAD

**Issue by jesseschalken** [fredemmott/definition-finder#51]
Namespace-relative names like `namespace\foo(..)` result in an exception when parsed. Presumably the parser isn't expecting a `T_NAMESPACE` in that position.

Example:

```php
<?hh

namespace FredEmmott\DefinitionFinder;

require_once __DIR__.'/vendor/autoload.php';

function main() {
  print FileParser::FromData('<?hh
  function foo(): void {
    namespace\strpos();
  }
  ', 'file.php');
}

main();
```
```
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Unexpected token '('' in /definition-finder/src/consumers/NamespaceConsumer.php:23
Stack trace:
#0 /definition-finder/src/consumers/NamespaceConsumer.php(23): HH\invariant_violation()
#1 /definition-finder/src/consumers/ScopeConsumer.php(312): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#2 /definition-finder/src/consumers/ScopeConsumer.php(277): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#3 /definition-finder/src/FileParser.php(21): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#4 /definition-finder/src/FileParser.php(45): FredEmmott\DefinitionFinder\FileParser->__construct()
#5 /test.php(12): FredEmmott\DefinitionFinder\FileParser::FromData()
#6 /test.php(15): FredEmmott\DefinitionFinder\main()
#7 {main}

Next exception 'FredEmmott\DefinitionFinder\ParseException' with message 'file.php:3: Unexpected token '('' in /definition-finder/src/FileParser.php:26
Stack trace:
#0 /definition-finder/src/FileParser.php(45): FredEmmott\DefinitionFinder\FileParser->__construct()
#1 /test.php(12): FredEmmott\DefinitionFinder\FileParser::FromData()
#2 /test.php(15): FredEmmott\DefinitionFinder\main()
#3 {main}
```

**Comment by fredemmott** [comment]
Is this specifically when you have a namespace called 'namespace' ?

**Comment by fredemmott** [comment]
TIL http://php.net/manual/en/language.namespaces.nsconstants.php example 4 and below...
